# Generated by Django 2.1.8 on 2021-10-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='schoolclass',
        ),
        migrations.AddField(
            model_name='group',
            name='lesson_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='time',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
